# Generated by Django 4.2.13 on 2025-06-14 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='The official name of the business.', max_length=100, unique=True)),
                ('business_structure', models.CharField(choices=[('LLC', 'Limited Liability Company (LLC)'), ('Corporation', 'Corporation'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership')], help_text='Legal structure of the business (e.g., LLC, Corporation).', max_length=20)),
                ('industry_category', models.CharField(help_text='Category of industry the business operates in (e.g., Tech, Retail, Food).', max_length=100)),
                ('funding_goal', models.DecimalField(decimal_places=2, help_text='Total amount of funding the business aims to raise.', max_digits=15)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of funding raised so far.', max_digits=15)),
                ('minimum_investment', models.DecimalField(decimal_places=2, help_text='Minimum amount an investor can contribute.', max_digits=15)),
                ('employee_count', models.IntegerField(default=0, help_text='Number of employees working for the business.')),
                ('address', models.TextField(help_text='Physical address of the business.')),
                ('city', models.CharField(help_text='City where the business is located.', max_length=100)),
                ('country', models.CharField(help_text='Country where the business is located.', max_length=100)),
                ('website_url', models.URLField(blank=True, help_text='Official website URL of the business.', max_length=255, null=True)),
                ('business_description', models.TextField(help_text='Detailed description of the business, its mission, and operations.')),
                ('historical_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Past revenue figures (e.g., last fiscal year).', max_digits=15, null=True)),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Expected future revenue projections.', max_digits=15, null=True)),
                ('current_valuation', models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated valuation of the business.', max_digits=15, null=True)),
                ('business_status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='active', help_text='Current operational status of the business.', max_length=10)),
                ('launch_date', models.DateField(blank=True, help_text='Date the business was officially launched.', null=True)),
                ('next_report_due', models.DateField(blank=True, help_text='Date when the next progress or financial report is due.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the business record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to the business record.')),
                ('entrepreneur', models.ForeignKey(help_text='The entrepreneur who owns this business.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
