# Generated by Django 4.2.13 on 2025-06-28 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum investment amount (optional)', max_digits=12, null=True)),
                ('investment_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum investment amount (optional)', max_digits=12, null=True)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('accredited_investor_status', models.BooleanField(default=False)),
                ('proof_of_accreditation', models.FileField(blank=True, help_text='Upload proof of accredited investor status', null=True, upload_to='investor_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_industries', models.ManyToManyField(blank=True, help_text='Select preferred industries for investment', to='investors.industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Profile',
                'verbose_name_plural': 'Investor Profiles',
            },
        ),
    ]
