# Generated by Django 4.2.13 on 2025-06-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='investorprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='investment_range_max',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='investment_range_min',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='preferred_industries',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='proof_of_accreditation',
        ),
        migrations.AddField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the industry.', null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief biography of the investor.', null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='current_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current available funds for the investor to deploy.', max_digits=12),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investment_focus',
            field=models.ManyToManyField(blank=True, help_text='The industries the investor is interested in.', related_name='investors', to='investors.industry'),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text="Link to the investor's LinkedIn profile.", null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='max_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum investment amount the investor considers.', max_digits=12),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='min_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum investment amount the investor considers.', max_digits=12),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='website',
            field=models.URLField(blank=True, help_text="Investor's personal or company website.", null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(help_text="Name of the industry (e.g., 'Technology', 'Healthcare').", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='accredited_investor_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], default='no', help_text='Accredited investor status.', max_length=10),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='risk_tolerance',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text="Investor's tolerance for risk.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='user',
            field=models.OneToOneField(help_text='The CustomUser associated with this investor profile.', limit_choices_to={'user_type': 'investor'}, on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
