# Generated by Django 4.2.13 on 2025-06-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_alter_industry_options_alter_investorprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='current_fund',
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount invested in this transaction.', max_digits=12)),
                ('investment_date', models.DateTimeField(auto_now_add=True, help_text='The date and time of the investment.')),
                ('business', models.ForeignKey(help_text='The business that received this investment.', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.business')),
                ('investor_profile', models.ForeignKey(help_text='The investor who made this investment.', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.investorprofile')),
            ],
            options={
                'ordering': ['-investment_date'],
            },
        ),
    ]
