# Generated by Django 5.2.1 on 2025-06-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_business_remove_investorprofile_current_fund_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
