# Generated by Django 5.2.1 on 2025-06-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('backers', models.IntegerField(default=0)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team_size', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True, null=True)),
                ('social_media', models.CharField(blank=True, max_length=100, null=True)),
                ('business_plan', models.TextField(blank=True, null=True)),
                ('financial_projections', models.TextField(blank=True, null=True)),
                ('market_analysis', models.TextField(blank=True, null=True)),
                ('competitive_advantage', models.TextField(blank=True, null=True)),
                ('use_of_funds', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('size', models.CharField(max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investments.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='investments.business')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('duration', models.CharField(max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='investments.business')),
            ],
        ),
    ]
