# Generated by Django 5.2.1 on 2025-06-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdocument',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='businessimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='businessvideo',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='business_documents/'),
        ),
        migrations.AddField(
            model_name='businessimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
        migrations.AddField(
            model_name='businessvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='business_videos/'),
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
