# Generated by Django 5.2.1 on 2025-06-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_remove_businessdocument_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='business_thumbnails/'),
        ),
    ]
