# Generated by Django 5.2.1 on 2025-06-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_businessvideo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='entrepreneur_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
