# Generated by Django 4.2.13 on 2025-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_business_entrepreneur_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='founding_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='growth_metrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='industry_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='key_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='revenue_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='target_market_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
