# Generated by Django 4.2.13 on 2025-06-22 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0006_business_created_at_business_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('fund_usage', models.TextField(help_text='How the funds are being used')),
                ('progress_update', models.TextField(help_text='Progress made with the funds')),
                ('achievements', models.TextField(help_text='Key achievements and milestones')),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced and how they were overcome', null=True)),
                ('next_steps', models.TextField(help_text='Planned next steps')),
                ('financial_update', models.TextField(help_text='Financial performance and metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='investments.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
