# Generated by Django 4.2.13 on 2025-06-22 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments_tracking', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='profit_distributed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit distributed to investors', max_digits=12),
        ),
        migrations.AddField(
            model_name='log',
            name='profit_distribution_date',
            field=models.DateTimeField(blank=True, help_text='Date when profit was distributed', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='profit_generated',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit generated in this period', max_digits=12),
        ),
        migrations.AddField(
            model_name='log',
            name='profit_notes',
            field=models.TextField(blank=True, help_text='Notes about profit generation and distribution', null=True),
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_distributed', models.DecimalField(decimal_places=2, help_text='Amount distributed to this investor', max_digits=12)),
                ('distribution_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total profit distributed to this investor', max_digits=5)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='investments_tracking.investment')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='logs.log')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-distributed_at'],
                'unique_together': {('log', 'investment')},
            },
        ),
    ]
