# Generated by Django 5.2.1 on 2025-06-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_savedbusiness'),
        ('logs', '0003_alter_log_achievements_alter_log_financial_update_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-year', '-month', '-created_at']},
        ),
        migrations.AddField(
            model_name='log',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month of the report', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total expenses for this month', max_digits=12),
        ),
        migrations.AddField(
            model_name='log',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue for this month', max_digits=12),
        ),
        migrations.AddField(
            model_name='log',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year of the report', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='profit_generated',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit generated in this period (calculated)', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('business', 'month', 'year')},
        ),
    ]
