# Generated by Django 5.2.1 on 2025-06-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_log_options_log_month_log_total_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
