# Generated by Django 4.2.13 on 2025-06-28 18:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='entrepreneur_profiles/')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('annual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('total_businesses_created', models.PositiveIntegerField(default=0)),
                ('total_funding_raised', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_investors', models.PositiveIntegerField(default=0)),
                ('total_profit_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, help_text='Success rate as a percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_investment_size', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_investment_range', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_industries', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrepreneur Profile',
                'verbose_name_plural': 'Entrepreneur Profiles',
            },
        ),
    ]
