# Generated by Django 4.2.13 on 2025-06-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('investor', 'Investor'), ('entrepreneur', 'Entrepreneur')], default='investor', help_text='Designates the type of user (investor or entrepreneur).', max_length=20),
        ),
    ]
