# Generated by Django 4.2.13 on 2025-06-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fund',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Available funds for the user', max_digits=12),
        ),
    ]
